"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");

const {
  ASSIGNABLE_PRESET_VALUES,
  PROTECTED_SUPER_ADMIN_EMAILS,
  buildAccessConfiguration,
  customPermissionsUseAssignedScope,
  isProtectedSuperAdminEmail,
  normalizeEmail,
  sanitizeAssignedClientIds,
  sanitizeCustomPermissions,
} = require("../adminAccessManagement");

test(
  "all three permanent Super Admin emails are protected",
  () => {
    assert.equal(
      PROTECTED_SUPER_ADMIN_EMAILS.length,
      3
    );

    for (
      const email of
      PROTECTED_SUPER_ADMIN_EMAILS
    ) {
      assert.equal(
        isProtectedSuperAdminEmail(
          email.toUpperCase()
        ),
        true
      );
    }
  }
);

test(
  "unlisted emails are not protected Super Admins",
  () => {
    assert.equal(
      isProtectedSuperAdminEmail(
        "ordinary@example.com"
      ),
      false
    );
  }
);

test(
  "email normalisation trims and lowercases",
  () => {
    assert.equal(
      normalizeEmail(
        "  Valentine@Example.COM "
      ),
      "valentine@example.com"
    );
  }
);

test(
  "Super Admin is not an assignable preset",
  () => {
    assert.equal(
      ASSIGNABLE_PRESET_VALUES.includes(
        "super_admin"
      ),
      false
    );
  }
);

test(
  "assigned client IDs are cleaned and deduplicated",
  () => {
    assert.deepEqual(
      sanitizeAssignedClientIds([
        "client-a",
        " client-a ",
        "client-b",
      ]),
      ["client-a", "client-b"]
    );
  }
);

test(
  "invalid assigned client IDs are rejected",
  () => {
    assert.throws(
      () =>
        sanitizeAssignedClientIds([
          "clients/client-a",
        ]),
      /invalid/
    );
  }
);

test(
  "standard presets ignore no browser-defined permissions",
  () => {
    assert.throws(
      () =>
        buildAccessConfiguration({
          enabled: true,
          active: true,
          preset:
            "operations_admin",
          assignedClientIds: [],
          permissions: {
            adminManagement: true,
          },
        }),
      /generated by the server/
    );
  }
);

test(
  "an assigned preset requires at least one client",
  () => {
    assert.throws(
      () =>
        buildAccessConfiguration({
          enabled: true,
          active: true,
          preset:
            "assigned_client_viewer",
          assignedClientIds: [],
          permissions: {},
        }),
      /At least one assigned client/
    );
  }
);

test(
  "all-client preset removes supplied assignments",
  () => {
    const access =
      buildAccessConfiguration({
        enabled: true,
        active: true,
        preset:
          "all_client_viewer",
        assignedClientIds: [
          "client-a",
        ],
        permissions: {},
      });

    assert.deepEqual(
      access.assignedClientIds,
      []
    );
  }
);

test(
  "custom permissions reject unknown fields",
  () => {
    assert.throws(
      () =>
        sanitizeCustomPermissions({
          secretPermission: true,
        }),
      /unsupported field/
    );
  }
);

test(
  "custom permissions reject invalid scopes",
  () => {
    assert.throws(
      () =>
        sanitizeCustomPermissions({
          clients: {
            view: "owner",
          },
        }),
      /must be none, assigned or all/
    );
  }
);

test(
  "custom permissions cannot grant admin management",
  () => {
    assert.throws(
      () =>
        sanitizeCustomPermissions({
          adminManagement: true,
        }),
      /cannot grant/
    );
  }
);

test(
  "custom permissions are normalised with safe defaults",
  () => {
    const permissions =
      sanitizeCustomPermissions({
        clients: {
          view: "all",
        },
        users: {
          view: true,
        },
      });

    assert.equal(
      permissions.clients.view,
      "all"
    );

    assert.equal(
      permissions.clients.edit,
      "none"
    );

    assert.equal(
      permissions.users.view,
      true
    );

    assert.equal(
      permissions.users.manage,
      false
    );

    assert.equal(
      permissions.adminManagement,
      false
    );
  }
);

test(
  "custom assigned scopes are detected",
  () => {
    const permissions =
      sanitizeCustomPermissions({
        shifts: {
          view: "assigned",
        },
      });

    assert.equal(
      customPermissionsUseAssignedScope(
        permissions
      ),
      true
    );
  }
);

test(
  "custom assigned scope requires an assigned client",
  () => {
    assert.throws(
      () =>
        buildAccessConfiguration({
          enabled: true,
          active: true,
          preset: "custom",
          assignedClientIds: [],
          permissions: {
            invoices: {
              view: "assigned",
            },
          },
        }),
      /At least one assigned client/
    );
  }
);

test(
  "valid custom access is sanitised",
  () => {
    const access =
      buildAccessConfiguration({
        enabled: true,
        active: true,
        preset: "custom",
        assignedClientIds: [
          "client-a",
        ],
        permissions: {
          clients: {
            view: "assigned",
            edit: "none",
          },
          staffPortalAccess: true,
          payroll: {
            view: true,
            manage: false,
          },
          adminManagement: false,
        },
      });

    assert.equal(
      access.preset,
      "custom"
    );

    assert.equal(
      access.active,
      true
    );

    assert.deepEqual(
      access.assignedClientIds,
      ["client-a"]
    );

    assert.equal(
      access.permissions
        .adminManagement,
      false
    );
  }
);